# Problem 96
## [Su Doku](https://projecteuler.net/problem=96)

<p>Su Doku (Japanese meaning <i>number place</i>) is the name given to a popular puzzle concept. Its origin is unclear, but credit must be attributed to Leonhard Euler who invented a similar, and much more difficult, puzzle idea called Latin Squares. The objective of Su Doku puzzles, however, is to replace the blanks (or zeros) in a 9 by 9 grid in such that each row, column, and 3 by 3 box contains each of the digits 1 to 9. Below is an example of a typical starting puzzle grid and its solution grid.</p>
<div class="center">
<img src="https://projecteuler.net/project/images/p096_1.png" alt="p096_1.png" />     <img src="https://projecteuler.net/project/images/p096_2.png" alt="p096_2.png" />
</div>
<p>A well constructed Su Doku puzzle has a unique solution and can be solved by logic, although it may be necessary to employ "guess and test" methods in order to eliminate options (there is much contested opinion over this). The complexity of the search determines the difficulty of the puzzle; the example above is considered <i>easy</i> because it can be solved by straight forward direct deduction.</p>
<p>The 6K text file, <a href="https://projecteuler.net/project/resources/p096_sudoku.txt">sudoku.txt</a> (right click and 'Save Link/Target As...'), contains fifty different Su Doku puzzles ranging in difficulty, but all with unique solutions (the first puzzle in the file is the example above).</p>
<p>By solving all fifty puzzles find the sum of the 3-digit numbers found in the top left corner of each solution grid; for example, 483 is the 3-digit number found in the top left corner of the solution grid above.</p>

In [235]:
sudoku = []
with open('p096_sudoku.txt', 'r') as f:
    sudoku = f.read().splitlines()


In [236]:
len(sudoku)

500

In [244]:
temp = []
for i in range(50):
    s = sudoku[i*10+1:i*10+10]
    s = np.array([list(map(int, list(i))) for i in s])
    temp.append(s)
sudoku = temp

In [245]:
import numpy as np
from collections import Counter

In [246]:
def check_row(a):
    c = Counter(list(a))
    for k, v in c.items():
        if k != 0 and v > 1:
            return False
    return True

In [247]:
def check(sudoku):
    for i in range(9):
        row = sudoku[i]
        if not check_row(row):
            return False
        col = sudoku[:, i]
        if not check_row(col):
            return False
    for i in range(3):
        for j in range(3):
            block = sudoku[i*3:i*3+3, j*3:j*3+3].reshape((-1))
            if not check_row(block):
                return False
    return True
            

In [248]:
def valid(sudoku):
    if 0 in sudoku:
        return False
    elif check(sudoku):
        return True
    return False

In [253]:
def valid_num(puzzle, i, v):
    row_i, col_j = i//9, i%9
    row = puzzle[row_i]
    if v in row:
        return False
    col = puzzle[:, col_j]
    if v in col:
        return False
    block = puzzle[row_i//3*3:row_i//3*3+3, col_j//3*3:col_j//3*3+3]
    if v in block:
        return False
    return True

In [250]:
def backtrack(puzzle, i):
    if valid(puzzle):
        return [True, puzzle]
    if puzzle[i//9][i%9] != 0:
        return backtrack(puzzle, i+1)
    if not check(puzzle):
        return [False, None]
    for v in range(1, 10):
        if not valid_num(puzzle, i, v):
            continue
        puzzle[i//9][i%9] = v
        res = backtrack(puzzle, i+1)
        if res[0] == True:
            return res
    puzzle[i//9][i%9] = 0
    return [False, None]
    

In [251]:
def solve(sudoku):
    return backtrack(sudoku, 0)

In [252]:
%%timeit -n1 -r1
s = 0
for su in sudoku:
    ans = solve(su.copy())[1][0, :3]
    print(ans)
    s += ans[0]*100 + ans[1]*10 + ans[2]
print(s)

[4 8 3]
[2 4 5]
[4 6 2]
[1 3 7]
[5 2 3]
[1 7 6]
[1 4 3]
[4 8 7]
[8 1 4]
[7 6 1]
[9 7 6]
[9 6 2]
[3 9 7]
[6 3 9]
[6 9 7]
[3 6 1]
[3 5 9]
[7 8 6]
[7 4 3]
[7 8 2]
[4 2 8]
[4 2 5]
[3 4 8]
[1 2 4]
[3 6 1]
[5 8 1]
[3 8 7]
[3 4 5]
[2 3 5]
[2 9 8]
[7 6 1]
[1 3 2]
[6 9 8]
[8 5 2]
[4 5 3]
[5 1 6]
[9 4 5]
[3 6 5]
[1 3 4]
[1 9 3]
[8 1 4]
[3 8 4]
[4 6 9]
[3 1 6]
[5 8 6]
[9 5 4]
[1 5 9]
[8 6 1]
[2 9 4]
[3 5 1]
24702
3min 21s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
